config:
  credentials: []
  project_repos:
    github.com/Accenture/sfmc-devtools-copado:
      branch: main
      repo: https://github.com/Accenture/sfmc-devtools-copado
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Accenture/sfmc-devtools-copado git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cinnamon-paradise.sh
        container: qc.acc_clammy-dandelion-albatross
  QC.Doc:
    repos:
      github.com/Accenture/sfmc-devtools-copado find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chartreuse-coati.sh
        container: qc.doc_grumpy-xanthic-akbash
      github.com/Accenture/sfmc-devtools-copado git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-black-hamster.sh
        container: qc.doc_shaky-violet-catfish
      github.com/Accenture/sfmc-devtools-copado markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-lilac-ragdoll.sh
        container: qc.doc_gamy-dandelion-gibbon
  QC.Lic:
    repos:
      github.com/Accenture/sfmc-devtools-copado licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-goldenrod-snail.sh
        container: qc.lic_dorky-amethyst-chimpanzee
  QC.Sty:
    repos:
      github.com/Accenture/sfmc-devtools-copado hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-coral-clam.sh
        container: qc.sty_bumpy-crimson-ostrich
      github.com/Accenture/sfmc-devtools-copado jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-seashell-jackal.sh
        container: qc.sty_trippy-zucchini-ferret
  QC.Ver:
    repos:
      github.com/Accenture/sfmc-devtools-copado get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-harlequin-manatee.sh
        container: qc.ver_snazzy-zucchini-bongo
timeout: 5400
